In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2 , 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
arr2 = np.array([[1,2,3] , [3, 4, 5]])
arr2

array([[1, 2, 3],
       [3, 4, 5]])

In [5]:
zeroes = np.zeros((2,3))
zeroes
                  

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
ones = np.ones((3,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
arange = np.arange(0 , 10 , 2)
arange

array([0, 2, 4, 6, 8])

In [8]:
lin = np.linspace(0 , 10 , 6)
lin

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [9]:
zeroes.shape

(2, 3)

In [10]:
arange.shape

(5,)

In [11]:
lin = lin.reshape(2 , 3)
lin

array([[ 0.,  2.,  4.],
       [ 6.,  8., 10.]])

In [12]:
arange.ndim


1

In [13]:
arr3 = np.array([1, 2, 3])
print(arr3 * 2 )
arr4 = np.array([4, 5, 6])
print(arr3 + arr4)

[2 4 6]
[5 7 9]


In [14]:
arr5 = np.array([[1, 3, 4] , [5,6,7]])
arr6 = np.array([[[1,2,3] ,[5, 6, 7],[8, 9, 10]]])
print(np.dot(arr5 , arr6))

[[[ 48  56  64]]

 [[ 91 109 127]]]


In [15]:
arr5

array([[1, 3, 4],
       [5, 6, 7]])

In [16]:
print(arr5[1][1])

6


In [17]:
print(arr5[: , 2])

[4 7]


In [18]:
arr6

array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 8,  9, 10]]])

In [19]:
print(arr6[0 , 1 ,
            1 ])

6


In [20]:
print(arr6[0:2 ,0])

[[1 2 3]]


In [21]:
print(arr6[arr6>3])

[ 5  6  7  8  9 10]


In [22]:
arr7 = np.array([1, 4 ,9])
print(np.sqrt(arr7))
print(np.exp(arr7))

[1. 2. 3.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03]


In [23]:
print(np.mean(arr7))
print(np.sum(arr7))
print(np.std(arr7))
print(np.var(arr7))


4.666666666666667
14
3.2998316455372216
10.888888888888888


In [24]:
np.random.seed(42)
arr8 = np.random.rand(2, 3)
arr8

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452]])

In [29]:
X = np.array([
[1.2 , 2.5 , 3.1] ,
[0.8 , 1.9 , 2.7],
[1.5 , 3.0 ,4.0] ,
[0.9 , 2.1  ,3.3]
])

X_mean = np.mean(X , axis=0)
X_mean

array([1.1  , 2.375, 3.275])

In [31]:
X_std = np.std(X  , axis=0)
X_std

array([0.27386128, 0.4205651 , 0.47103609])

In [32]:
X_stand = (X - X_mean) / X_std
X_stand

array([[ 0.36514837,  0.29721915, -0.37152142],
       [-1.09544512, -1.12943277, -1.22071325],
       [ 1.46059349,  1.48609575,  1.53916019],
       [-0.73029674, -0.65388213,  0.05307449]])

In [34]:
X_min = np.min(X , axis=0)
X_max = np.max(X , axis= 0)
X_norm = (X - X_min) / X_max
X_norm

array([[0.26666667, 0.2       , 0.1       ],
       [0.        , 0.        , 0.        ],
       [0.46666667, 0.36666667, 0.325     ],
       [0.06666667, 0.06666667, 0.15      ]])

In [ ]:
#mini_project
#ANN_numpy

In [43]:
np.random.seed(42)
n_samples_per_class = 100
class1 = np.random.multivariate_normal([2, 2], [[1, 0.5], [0.5, 1]], n_samples_per_class)
class2 = np.random.multivariate_normal([-2, -2], [[1, 0.5], [0.5, 1]], n_samples_per_class)
X = np.vstack((class1, class2))
y = np.hstack((np.zeros(n_samples_per_class), np.ones(n_samples_per_class)))

In [44]:
input_size, hidden_size, output_size = 2, 10, 1
learning_rate, epochs = 0.01, 1000
W1 = np.random.randn(input_size, hidden_size) * 0.01
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size) * 0.01
b2 = np.zeros((1, output_size))

In [45]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [46]:
def forward_propagation(X):
    Z1 = np.dot(X, W1) + b1
    A1 = np.tanh(Z1)
    Z2 = np.dot(A1, W2) + b2
    A2 = sigmoid(Z2)
    return Z1, A1, Z2, A2

In [47]:
def compute_loss(y_true, y_pred):
    y_pred = np.clip(y_pred, 1e-10, 1 - 1e-10)
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

In [48]:
def backward_propagation(X, y, Z1, A1, Z2, A2):
    m = X.shape[0] 
    dZ2 = A2 - y.reshape(-1, 1) 
    dW2 = np.dot(A1.T, dZ2) / m
    db2 = np.sum(dZ2, axis=0, keepdims=True) / m
    dA1 = np.dot(dZ2, W2.T)
    dZ1 = dA1 * (1 - np.tanh(Z1) ** 2)
    dW1 = np.dot(X.T, dZ1) / m
    db1 = np.sum(dZ1, axis=0, keepdims=True) / m
    return dW1, db1, dW2, db2

In [49]:
for epoch in range(epochs):
    Z1, A1, Z2, A2 = forward_propagation(X)
    loss = compute_loss(y, A2) 
    dW1, db1, dW2, db2 = backward_propagation(X, y, Z1, A1, Z2, A2)
    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1
    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2
    if (epoch + 1) % 100 == 0:
        print(f"Epoch {epoch + 1}, Loss: {loss:.4f}")

Epoch 100, Loss: 0.6933
Epoch 200, Loss: 0.7131
Epoch 300, Loss: 0.8767
Epoch 400, Loss: 1.1150
Epoch 500, Loss: 1.3174
Epoch 600, Loss: 1.4779
Epoch 700, Loss: 1.6073
Epoch 800, Loss: 1.7144
Epoch 900, Loss: 1.8050
Epoch 1000, Loss: 1.8833


In [50]:
predictions = forward_propagation(X)[-1]
predictions = (predictions > 0.5).astype(int).flatten()
accuracy = np.mean(predictions == y)
print(f"Accuracy: {accuracy:.4f}")

Accuracy: 0.9950
